### ISSUE TITLE
ArcoLinuxD Openbox

### ISSUE THREAD

**Issue by ThavaNix** [arcolinuxd/arco-openbox#1]
When i installed ArcolinuxD Openbox thats did not install polkit-gnome and xdg-user-dirs-update.
They can't use pamac with polkit-gnome.

**Comment by arcolinuxz** [comment]
thanks we will check it upon next installation

**Comment by arcolinuxz** [comment]
I tested it with arcolinuxd 6.7.1. - running all scripts except Personal folder

1. polkit-gnome : polkit and polkit-gnome are installed 

2. xdg-user-dirs : that one is installed and we end up with all folders created in the home folder - so that is good
